"use client";

import { useMemo, useState } from "react";

type Priority = "Urgent" | "High" | "Normal";
type WorkState = "In progress" | "To do" | "Waiting";
type Assignment = { id:string; title:string; account:string; amount:number; priority:Priority; state:WorkState; due:string; source:string; reason:string; owner:string };

const navItems = [["Overview","⌂"],["Exceptions","!","128"],["Reconciliation","⇄","24"],["Assignments","✓","17"],["Reports","▥"]];
const initialAssignments:Assignment[] = [
  {id:"EXC-2048",title:"Duplicate settlement detected",account:"Northstar Retail",amount:18450,priority:"Urgent",state:"In progress",due:"Due in 42 min",source:"Stripe",reason:"Duplicate payment",owner:"Maya Chen"},
  {id:"EXC-2039",title:"Settlement amount mismatch",account:"Apex Health",amount:12780,priority:"High",state:"To do",due:"Due today, 1:30 PM",source:"Adyen",reason:"Amount mismatch",owner:"Maya Chen"},
  {id:"EXC-2027",title:"Missing settlement reference",account:"Metro Transit",amount:9420.5,priority:"Normal",state:"Waiting",due:"Due today, 4:00 PM",source:"JPMorgan",reason:"Missing reference",owner:"Maya Chen"},
  {id:"EXC-2014",title:"Currency conversion variance",account:"Greenway Foods",amount:8205,priority:"High",state:"To do",due:"Due tomorrow, 10:00 AM",source:"Stripe",reason:"FX variance",owner:"Maya Chen"},
  {id:"EXC-1998",title:"Processor fee discrepancy",account:"Harbor Logistics",amount:5280,priority:"Normal",state:"In progress",due:"Due tomorrow, 2:00 PM",source:"Adyen",reason:"Fee mismatch",owner:"Maya Chen"},
];
const unassigned:Assignment[] = [
  {id:"EXC-2053",title:"Unrecognized bank return",account:"Summit Wireless",amount:6740.25,priority:"Urgent",state:"To do",due:"SLA in 18 min",source:"JPMorgan",reason:"Bank return",owner:"Unassigned"},
  {id:"EXC-2051",title:"Partial capture not settled",account:"BluePeak Energy",amount:11820,priority:"High",state:"To do",due:"SLA in 1h 24m",source:"Checkout.com",reason:"Partial capture",owner:"Unassigned"},
  {id:"EXC-2044",title:"Refund exceeds captured amount",account:"Luna Markets",amount:4360,priority:"Normal",state:"To do",due:"SLA in 3h 06m",source:"Stripe",reason:"Refund mismatch",owner:"Unassigned"},
];
const team = [
  {name:"Maya Chen",initials:"MC",role:"You",open:5,capacity:72,color:"lilac"},{name:"Jon Bell",initials:"JB",role:"Analyst",open:4,capacity:58,color:"sky"},{name:"Priya Shah",initials:"PS",role:"Analyst",open:7,capacity:88,color:"peach"},{name:"Alex Morgan",initials:"AM",role:"Analyst",open:2,capacity:34,color:"mint"},
];
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value%1?2:0}).format(value);
function PriorityBadge({priority}:{priority:Priority}){return <span className={`priority ${priority.toLowerCase()}`}><i/>{priority}</span>}
function StateBadge({state}:{state:WorkState}){return <span className={`state ${state.toLowerCase().replaceAll(" ","-")}`}>{state}</span>}

export default function Home(){
  const [active,setActive]=useState("Assignments"),[menuOpen,setMenuOpen]=useState(false),[query,setQuery]=useState(""),[tab,setTab]=useState("All");
  const [selected,setSelected]=useState<Assignment|null>(null),[assigned,setAssigned]=useState(initialAssignments),[unowned,setUnowned]=useState(unassigned),[toast,setToast]=useState("");
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return assigned.filter(item=>(tab==="All"||item.state===tab)&&(!term||[item.id,item.title,item.account,item.source,item.reason].some(value=>value.toLowerCase().includes(term))))},[assigned,query,tab]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  const assignToMe=(item:Assignment)=>{const next={...item,owner:"Maya Chen"};setUnowned(current=>current.filter(entry=>entry.id!==item.id));setAssigned(current=>[next,...current]);setSelected(next);notify(`${item.id} assigned to you`)};
  const completeSelected=()=>{if(!selected)return;setAssigned(current=>current.filter(item=>item.id!==selected.id));setSelected(null);notify("Assignment marked complete")};
  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen?"open":""}`}><div className="brand"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><div><strong>ClearFlow</strong><span>Payment operations</span></div><button type="button" className="close-nav" onClick={()=>setMenuOpen(false)} aria-label="Close navigation">×</button></div><p className="nav-label">Workspace</p><nav className="nav-stack" aria-label="Workspace navigation">{navItems.map(([label,icon,count])=><button key={label} type="button" className={active===label?"active":""} onClick={()=>{setActive(label);setMenuOpen(false)}}><span className="nav-glyph">{icon}</span><span>{label}</span>{count&&<b>{count}</b>}</button>)}</nav><p className="nav-label manage-label">Manage</p><nav className="nav-stack" aria-label="Manage"><button type="button"><span className="nav-glyph">⚙</span><span>Settings</span></button><button type="button"><span className="nav-glyph">◇</span><span>Admin</span></button></nav><div className="side-spacer"/><div className="close-card"><span className="pulse-dot"/><div><strong>Books close in 3 days</strong><span>August close · 82% complete</span></div><button type="button" onClick={()=>notify("Close checklist opened")}>→</button></div><div className="profile"><span className="avatar lilac">MC</span><div><strong>Maya Chen</strong><span>Operations lead</span></div><button type="button" aria-label="Profile options">•••</button></div></aside>
    {menuOpen&&<button className="mobile-scrim" type="button" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}<main><header className="topbar"><button className="menu-button" type="button" onClick={()=>setMenuOpen(true)}>Menu</button><label className="search"><span aria-hidden="true">⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search assignments, accounts or IDs" aria-label="Search assignments"/><kbd>⌘ K</kbd></label><div className="top-actions"><button className="icon-button" type="button" aria-label="Notifications">♢<i/></button><button className="primary-button" type="button" onClick={()=>notify("New assignment form opened")}><span>＋</span> Create assignment</button></div></header>
      <div className="dashboard"><section className="page-title"><div><p className="eyebrow">OPERATIONS / ASSIGNMENTS</p><h1>Good morning, Maya</h1><p>Here’s what needs your attention today.</p></div><div className="date-card"><span>Today</span><strong>Wednesday, August 19</strong></div></section>
        <section className="kpi-grid" aria-label="Assignment summary"><article><div className="kpi-top"><span className="metric-icon indigo">✓</span><em className="delta good">↑ 2 today</em></div><strong>{assigned.length}</strong><span>My open assignments</span><i className="metric-bar"><b style={{width:"64%"}}/></i></article><article><div className="kpi-top"><span className="metric-icon coral">!</span><em className="delta bad">2 need action</em></div><strong>3</strong><span>Due today</span><p>Next due in 42 minutes</p></article><article><div className="kpi-top"><span className="metric-icon amber">⌁</span><em className="delta neutral">Past 7 days</em></div><strong>11</strong><span>Completed this week</span><p><i className="mini-avatars"><b>MC</b><b>JB</b><b>PS</b></i> Team completed 46</p></article><article><div className="kpi-top"><span className="metric-icon green">◷</span><em className="delta good">↓ 18m</em></div><strong>2h 14m</strong><span>Average resolution time</span><p>12% faster than last week</p></article></section>
        <section className="work-grid"><article className="panel assignments-panel"><div className="panel-heading"><div><div className="heading-line"><h2>My assignments</h2><span>{assigned.length}</span></div><p>Exceptions currently assigned to you</p></div><button type="button" className="sort-button" onClick={()=>setAssigned(current=>[...current].sort((a,b)=>a.priority.localeCompare(b.priority)))}>↕ Sort</button></div><div className="tabs" role="tablist" aria-label="Assignment status">{["All","To do","In progress","Waiting"].map(label=><button key={label} role="tab" aria-selected={tab===label} type="button" className={tab===label?"selected":""} onClick={()=>setTab(label)}>{label}<b>{label==="All"?assigned.length:assigned.filter(item=>item.state===label).length}</b></button>)}</div><div className="assignment-list">{visible.length?visible.map(item=><button className="assignment-row" type="button" key={item.id} onClick={()=>setSelected(item)}><span className={`priority-rail ${item.priority.toLowerCase()}`}/><span className="assignment-main"><span className="row-meta"><PriorityBadge priority={item.priority}/><small>{item.id}</small></span><strong>{item.title}</strong><span className="account">{item.account}<i/>{item.source}</span></span><span className="amount"><small>EXPOSURE</small><strong>{money(item.amount)}</strong></span><span className="row-status"><StateBadge state={item.state}/><small className={item.priority==="Urgent"?"urgent-time":""}>◷ {item.due}</small></span><span className="chevron">›</span></button>):<div className="empty-state"><span>✓</span><strong>You’re all caught up</strong><p>No assignments match this view.</p><button type="button" onClick={()=>{setTab("All");setQuery("")}}>Clear filters</button></div>}</div><div className="panel-footer"><span>Showing {visible.length} of {assigned.length} assignments</span><button type="button" onClick={()=>{setTab("All");setQuery("")}}>View all assignments →</button></div></article>
          <aside className="side-column"><article className="panel workload-panel"><div className="panel-heading compact"><div><h2>Team workload</h2><p>Open assignments by analyst</p></div><button type="button" aria-label="Workload options">•••</button></div><div className="capacity-summary"><div className="capacity-ring"><span><strong>68%</strong><small>utilized</small></span></div><div><strong>18 open</strong><span>across 4 analysts</span><em>Healthy capacity</em></div></div><div className="team-list">{team.map(member=><div className="team-row" key={member.name}><span className={`avatar ${member.color}`}>{member.initials}</span><span className="member"><strong>{member.name}</strong><small>{member.role}</small></span><span className="capacity"><small>{member.open} open</small><i><b className={member.capacity>80?"hot":""} style={{width:`${member.capacity}%`}}/></i></span></div>)}</div><button className="text-link" type="button" onClick={()=>notify("Team capacity view opened")}>Manage team capacity <span>→</span></button></article><article className="panel sla-panel"><div className="panel-heading compact"><div><h2>SLA health</h2><p>Across active assignments</p></div><span className="health-pill"><i/> On track</span></div><div className="sla-number"><strong>94.2%</strong><span>within SLA</span></div><div className="sla-bars"><span><i><b className="safe" style={{width:"72%"}}/></i><small>13 healthy</small></span><span><i><b className="warn" style={{width:"17%"}}/></i><small>3 at risk</small></span><span><i><b className="danger" style={{width:"11%"}}/></i><small>2 breached</small></span></div></article></aside></section>
        <section className="panel unassigned-panel"><div className="panel-heading"><div><div className="heading-line"><h2>Needs assignment</h2><span className="coral-count">{unowned.length}</span></div><p>Unowned exceptions waiting for an analyst</p></div><button type="button" className="secondary-button" onClick={()=>notify("Assignment rules opened")}>⚙ Assignment rules</button></div><div className="unassigned-grid">{unowned.map(item=><article key={item.id} className="unassigned-card"><div><PriorityBadge priority={item.priority}/><small>{item.id}</small></div><h3>{item.title}</h3><p>{item.account} · {item.source}</p><dl><div><dt>Exposure</dt><dd>{money(item.amount)}</dd></div><div><dt>Reason</dt><dd>{item.reason}</dd></div></dl><div className="card-action"><span className={item.priority==="Urgent"?"urgent-time":""}>◷ {item.due}</span><button type="button" onClick={()=>assignToMe(item)}>Assign to me</button></div></article>)}</div>{!unowned.length&&<div className="unowned-empty">All exceptions have an owner. Nice work.</div>}</section>
      </div></main>{toast&&<div className="toast" role="status"><span>✓</span>{toast}</div>}
    {selected&&<div className="drawer-layer"><button type="button" className="drawer-backdrop" onClick={()=>setSelected(null)} aria-label="Close assignment detail"/><aside className="drawer" aria-label="Assignment detail"><div className="drawer-head"><div><p>{selected.id}</p><h2>{selected.title}</h2></div><button type="button" onClick={()=>setSelected(null)} aria-label="Close">×</button></div><div className="drawer-badges"><PriorityBadge priority={selected.priority}/><StateBadge state={selected.state}/></div><div className="deadline"><span>◷</span><div><small>RESOLUTION DEADLINE</small><strong>{selected.due}</strong></div></div><dl className="detail-grid"><div><dt>Account</dt><dd>{selected.account}</dd></div><div><dt>Exposure</dt><dd>{money(selected.amount)}</dd></div><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Owner</dt><dd>{selected.owner}</dd></div><div><dt>Exception reason</dt><dd>{selected.reason}</dd></div><div><dt>Status</dt><dd>{selected.state}</dd></div></dl><label className="notes">Resolution note<textarea placeholder="Add an update for your team…"/></label><div className="drawer-actions"><button type="button" className="secondary-button" onClick={()=>notify("Assignment saved for later")}>Save note</button><button type="button" className="primary-button" onClick={completeSelected}>✓ Mark complete</button></div></aside></div>}
  </div>
}
